import os
from dotenv import load_dotenv


load_dotenv()
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')
TAVILY_API_KEY = os.getenv('TAVILY_API_KEY')

POSTGRESDB_HOST = os.getenv('POSTGRESDB_HOST')
POSTGRESDB_PORT = os.getenv('POSTGRESDB_PORT')
POSTGRESDB_NAME = os.getenv('POSTGRESDB_NAME')
POSTGRESDB_USERNAME = os.getenv('POSTGRESDB_USERNAME')
POSTGRESDB_PASSWORD = os.getenv('POSTGRESDB_PASSWORD')

POSTGRESDB_RECORD_HOST = os.getenv('POSTGRESDB_RECORD_HOST')
POSTGRESDB_RECORD_PORT = os.getenv('POSTGRESDB_RECORD_PORT')
POSTGRESDB_RECORD_NAME = os.getenv('POSTGRESDB_RECORD_NAME')
POSTGRESDB_RECORD_USERNAME = os.getenv('POSTGRESDB_RECORD_USERNAME')
POSTGRESDB_RECORD_PASSWORD = os.getenv('POSTGRESDB_RECORD_PASSWORD')

CLICKHOUSE_HOST = os.getenv('CLICKHOUSE_HOST')
CLICKHOUSE_PORT = os.getenv('CLICKHOUSE_PORT')
CLICKHOUSE_USERNAME = os.getenv('CLICKHOUSE_USERNAME')
CLICKHOUSE_PASSWORD = os.getenv('CLICKHOUSE_PASSWORD')

REDIS_HOST = os.getenv('REDIS_HOST')
REDIS_PORT = os.getenv('REDIS_PORT')
REDIS_CLUSTER = os.getenv('REDIS_CLUSTER')
REDIS_DATABASE = os.getenv('REDIS_DATABASE')
REDIS_PASSWORD = os.getenv('REDIS_PASSWORD')

CONSUL_HOST = os.getenv('CONSUL_HOST')
CONSUL_USERNAME = os.getenv('CONSUL_USERNAME')
CONSUL_PASSWORD = os.getenv('CONSUL_PASSWORD')

OLLAMA_HOST = os.getenv('OLLAMA_HOST')
